"""
custom_cell_pipe
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from include.operators.api import InternalAPIOperator
import pendulum


default_args={
    "owner": "abhishek.bhakat@astronomer.io,Open in Cloud IDE",
}

@dag(
    default_args=default_args,
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2024-07-30", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
    owner_links={
        "abhishek.bhakat@astronomer.io": "mailto:abhishek.bhakat@astronomer.io",
        "Open in Cloud IDE": "https://cloud.astronomer.io/clvq8pnzb04g701o1qsb5kk1j/cloud-ide/clz89pgcm12wf01jy2o8gcl52/clz8a1zn812y101jypy6ui5xw",
    },
)
def custom_cell_pipe():
    call__internal__a_p_i_1 = InternalAPIOperator(
        task_id="call__internal__a_p_i_1",
    )

dag_obj = custom_cell_pipe()
