"""
snow_test
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from astro import sql as aql
import pandas as pd
import pendulum

from airflow.models import Connection
import os

@aql.dataframe(task_id="python_1")
def python_1_func():
    conn = Connection.get_connection_from_secrets('test_snowflake')
    print(conn.host)
    print(conn.conn_type)
    print(conn.debug_info())
    print(conn.get_uri())
    print(conn.extra)
    print(conn.__dict__)

@aql.dataframe(task_id="python_2")
def python_2_func():
    os.system('uname -a')
    os.system('hostname')

default_args={
    "owner": "Open in Cloud IDE",
}

@dag(
    default_args=default_args,
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2023-02-27", "YYYY-MM-DD").in_tz("Europe/London"),
    catchup=False,
    owner_links={
        "Open in Cloud IDE": "https://cloud.astronomer.io/cl0n1675p186971fwyfaumecrc/cloud-ide/cleiioon5008i01krj5dqtaku/clemeakko008u01osr2sa492h",
    },
)
def snow_test():
    python_1 = python_1_func()

    python_2 = python_2_func()

dag_obj = snow_test()
