"""
snow_test
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from astro import sql as aql
from astro.table import Table, Metadata
import pandas as pd
import pendulum

from airflow.models import Connection


@aql.dataframe(task_id="python_1")
def python_1_func():
    conn = Connection.get_connection_from_secrets('test_snowflake')
    print(conn.host)
    print(conn.conn_type)
    print(conn.debug_info())
    print(conn.get_uri())
    print(conn.extra)
    print(conn.__dict__)

@aql.transform(conn_id="test_snowflake", task_id="warehouse_sql_1")
def warehouse_sql_1_func():
    return """
    
    """

@dag(
    schedule_interval="0 0 * * *",
    start_date=pendulum.from_format("2023-02-27", "YYYY-MM-DD").in_tz("Europe/London"),
)
def snow_test():
    python_1 = python_1_func()

    warehouse_sql_1 = warehouse_sql_1_func()

dag_obj = snow_test()
