"""
test2
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from astro import sql as aql
import pandas as pd
import pendulum


@aql.dataframe(task_id="python_1")
def python_1_func():
    print("1")

@dag(
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2023-06-15", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
)
def test2():
    python_1 = python_1_func()

dag_obj = test2()
