"""
test_2
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from astro import sql as aql
from astro.table import Table, Metadata
import pandas as pd
import pendulum


@aql.dataframe(task_id="task1")
def task1_func():
    from time import sleep
    
    sleep(10)

@aql.run_raw_sql(conn_id="duckdb_default", task_id="sql_1", results_format="pandas_dataframe")
def sql_1_func():
    return """
    SELECT 1;
    """

default_args={
    "owner": "Open in Cloud IDE",
}

@dag(
    default_args=default_args,
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2023-05-04", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
    owner_links={
        "Open in Cloud IDE": "https://cloud.astronomer.io/cl0n1675p186971fwyfaumecrc/cloud-ide/cleiioon5008i01krj5dqtaku/clh988loa001c01qtz9257blo",
    },
)
def test_2():
    sql_1 = sql_1_func()

    task1 = task1_func()

    task1 << sql_1

dag_obj = test_2()
